###
#
# name: .pre-commit-config.yaml template
# source: https://github.com/kevinbowen777/git-hooks.git
# date: 20220423
#
###
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      exclude: ^migrations/versions/
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
#  - repo: https://github.com/pre-commit/mirrors-eslint
#  rev: v8.3.0
#  hooks:
#    - id: eslint
